Try to build executable via GraalVM (but fails)
Currently fails:

	$> docker build . -t hubstats

	Sending build context to Docker daemon  29.24MB
	Step 1/15 : FROM danny02/graalvm
	 ---> 59afedd44ee4
	Step 2/15 : COPY target/classes/ /target
	 ---> 13dc2ece9ae9
	Step 3/15 : WORKDIR /target
	Removing intermediate container f48cb5b05626
	 ---> 944902845b2c
	Step 4/15 : RUN native-image hubstats.core
	 ---> Running in 4474cd4f83f0
	Build on Server(pid: 12, port: 26681)*
	   classlist:   1,590.46 ms
	       (cap):   1,003.58 ms
	       setup:   2,087.04 ms
	    analysis:   1,890.83 ms
	fatal error: java.lang.NoClassDefFoundError
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
		at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
		at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
		at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:378)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:315)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:396)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:312)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:256)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:216)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.NoClassDefFoundError: clojure/lang/Var
		at hubstats.core.<clinit>(Unknown Source)
		at sun.misc.Unsafe.ensureClassInitialized(Native Method)
		at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.initialize(HotSpotResolvedObjectTypeImpl.java:381)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:211)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:191)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:168)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:67)
		at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:87)
		at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:78)
		at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:43)
		at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:519)
		at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:91)
		at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:77)
		at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:70)
		at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:111)
		at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:263)
		at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:307)
		at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:78)
		at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:60)
		at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:581)
		at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:552)
		at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:653)
		at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
		at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Caused by: java.lang.ClassNotFoundException: clojure.lang.Var
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 29 more
	Error: Processing image build request failed