Better, but still fails: "java.lang.ClassNotFoundException: org.joda.time.DateTime"
	$> docker build . -t hubstats

	Sending build context to Docker daemon  36.57MB
	Step 1/15 : FROM danny02/graalvm
	 ---> 59afedd44ee4
	Step 2/15 : COPY target/classes /target
	 ---> 3cd7f7cfff98
	Step 3/15 : WORKDIR /target
	Removing intermediate container 128116e55acb
	 ---> 6b1603b0f033
	Step 4/15 : RUN native-image hubstats.core
	 ---> Running in a1aa0e71d4ed
	Build on Server(pid: 12, port: 26681)*
	   classlist:   2,084.73 ms
	       (cap):     803.04 ms
	       setup:   1,665.65 ms
	    analysis:   2,232.71 ms
	fatal error: java.lang.ExceptionInInitializerError
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
		at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
		at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
		at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:378)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:315)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:396)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:312)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:256)
		at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:216)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.ExceptionInInitializerError
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at clojure.lang.RT.classForName(RT.java:2204)
		at clojure.lang.RT.classForName(RT.java:2213)
		at clojure.lang.RT.loadClassForName(RT.java:2232)
		at clojure.lang.RT.load(RT.java:450)
		at clojure.lang.RT.load(RT.java:426)
		at clojure.core$load$fn__6548.invoke(core.clj:6046)
		at clojure.core$load.invokeStatic(core.clj:6045)
		at clojure.core$load.doInvoke(core.clj:6029)
		at clojure.lang.RestFn.invoke(RestFn.java:408)
		at clojure.core$load_one.invokeStatic(core.clj:5848)
		at clojure.core$load_one.invoke(core.clj:5843)
		at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
		at clojure.core$load_lib.invokeStatic(core.clj:5887)
		at clojure.core$load_lib.doInvoke(core.clj:5868)
		at clojure.lang.RestFn.applyTo(RestFn.java:142)
		at clojure.core$apply.invokeStatic(core.clj:659)
		at clojure.core$load_libs.invokeStatic(core.clj:5925)
		at clojure.core$load_libs.doInvoke(core.clj:5909)
		at clojure.lang.RestFn.applyTo(RestFn.java:137)
		at clojure.core$apply.invokeStatic(core.clj:659)
		at clojure.core$require.invokeStatic(core.clj:5947)
		at clojure.core$require.doInvoke(core.clj:5947)
		at clojure.lang.RestFn.invoke(RestFn.java:482)
		at hubstats.github$loading__6434__auto____188.invoke(github.clj:1)
		at hubstats.github__init.load(Unknown Source)
		at hubstats.github__init.<clinit>(Unknown Source)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at clojure.lang.RT.classForName(RT.java:2204)
		at clojure.lang.RT.classForName(RT.java:2213)
		at clojure.lang.RT.loadClassForName(RT.java:2232)
		at clojure.lang.RT.load(RT.java:450)
		at clojure.lang.RT.load(RT.java:426)
		at clojure.core$load$fn__6548.invoke(core.clj:6046)
		at clojure.core$load.invokeStatic(core.clj:6045)
		at clojure.core$load.doInvoke(core.clj:6029)
		at clojure.lang.RestFn.invoke(RestFn.java:408)
		at clojure.core$load_one.invokeStatic(core.clj:5848)
		at clojure.core$load_one.invoke(core.clj:5843)
		at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
		at clojure.core$load_lib.invokeStatic(core.clj:5887)
		at clojure.core$load_lib.doInvoke(core.clj:5868)
		at clojure.lang.RestFn.applyTo(RestFn.java:142)
		at clojure.core$apply.invokeStatic(core.clj:659)
		at clojure.core$load_libs.invokeStatic(core.clj:5925)
		at clojure.core$load_libs.doInvoke(core.clj:5909)
		at clojure.lang.RestFn.applyTo(RestFn.java:137)
		at clojure.core$apply.invokeStatic(core.clj:659)
		at clojure.core$require.invokeStatic(core.clj:5947)
		at clojure.core$require.doInvoke(core.clj:5947)
		at clojure.lang.RestFn.invoke(RestFn.java:436)
		at hubstats.core$loading__6434__auto____186.invoke(core.clj:1)
		at hubstats.core__init.load(Unknown Source)
		at hubstats.core__init.<clinit>(Unknown Source)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at clojure.lang.RT.classForName(RT.java:2204)
		at clojure.lang.RT.classForName(RT.java:2213)
		at clojure.lang.RT.loadClassForName(RT.java:2232)
		at clojure.lang.RT.load(RT.java:450)
		at clojure.lang.RT.load(RT.java:426)
		at clojure.core$load$fn__6548.invoke(core.clj:6046)
		at clojure.core$load.invokeStatic(core.clj:6045)
		at clojure.core$load.doInvoke(core.clj:6029)
		at clojure.lang.RestFn.invoke(RestFn.java:408)
		at clojure.lang.Var.invoke(Var.java:381)
		at clojure.lang.Util.loadWithClass(Util.java:250)
		at hubstats.core.<clinit>(Unknown Source)
		at sun.misc.Unsafe.ensureClassInitialized(Native Method)
		at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.initialize(HotSpotResolvedObjectTypeImpl.java:381)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:211)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:191)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:168)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:67)
		at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:87)
		at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:78)
		at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:43)
		at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
		at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:519)
		at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:91)
		at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:77)
		at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:70)
		at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:111)
		at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:263)
		at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:307)
		at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:78)
		at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:60)
		at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:581)
		at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:552)
		at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:653)
		at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
		at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Caused by: java.lang.ClassNotFoundException: org.joda.time.DateTime
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at clojure.lang.RT.classForName(RT.java:2204)
		at clojure.lang.RT.classForName(RT.java:2213)
		at clj_time.core__init.__init1(Unknown Source)
		at clj_time.core__init.<clinit>(Unknown Source)
		... 98 more
Error: Processing image build request failed